from src.backend.services import jira_deduplicated_issue_service as svc


def test_upsert_deduplicated_jira_issue_reuses_existing_issue(monkeypatch):
    calls: list[tuple[str, dict]] = []

    def _fake_invoke(tool_name: str, payload: dict):
        calls.append((tool_name, payload))
        if tool_name == "jira_search":
            return {"success": True, "issues": [{"key": "JVNAUTOSCI-1600"}]}
        if tool_name == "jira_add_comment":
            return {"success": True}
        raise AssertionError(f"Unexpected tool call: {tool_name}")

    monkeypatch.setattr(svc, "_invoke_mcp_tool", _fake_invoke)

    result = svc.upsert_deduplicated_jira_issue(
        project_key="JVNAUTOSCI",
        issue_type="Task",
        summary="Episode critique remediation",
        description="Generated by Codex",
        fingerprint="abc123",
        search_label="episode-critique-remediation",
        existing_comment="Existing issue comment",
    )

    assert result["success"] is True
    assert result["mode"] == "updated_existing"
    assert result["issue_key"] == "JVNAUTOSCI-1600"
    assert [name for name, _ in calls] == ["jira_search", "jira_add_comment"]


def test_upsert_deduplicated_jira_issue_creates_issue_with_bounded_labels(monkeypatch):
    calls: list[tuple[str, dict]] = []

    def _fake_invoke(tool_name: str, payload: dict):
        calls.append((tool_name, payload))
        if tool_name == "jira_search":
            return {"success": True, "issues": []}
        if tool_name == "jira_get_myself":
            return {"success": True, "accountId": "acc-1"}
        if tool_name == "jira_create_issue":
            assert payload["assignee_account_id"] == "acc-1"
            assert payload["labels"] == [
                "episode-critique-remediation",
                "fp-abc123",
            ]
            return {"success": True, "issue_key": "JVNAUTOSCI-1610"}
        raise AssertionError(f"Unexpected tool call: {tool_name}")

    monkeypatch.setattr(svc, "_invoke_mcp_tool", _fake_invoke)

    result = svc.upsert_deduplicated_jira_issue(
        project_key="JVNAUTOSCI",
        issue_type="Task",
        summary="Episode critique remediation",
        description="Generated by Codex",
        fingerprint="abc123",
        search_label="episode-critique-remediation",
        labels="actor-critic",
    )

    assert result["success"] is True
    assert result["mode"] == "created_new"
    assert result["issue_key"] == "JVNAUTOSCI-1610"
    assert [name for name, _ in calls] == [
        "jira_search",
        "jira_get_myself",
        "jira_create_issue",
    ]
