// Reproducible, self-hosted browser assets. No CDN dependency at runtime.
import { build } from 'esbuild';
import { mkdir, cp, writeFile, rm } from 'node:fs/promises';
const outdir = 'src/frontend/web/von_interface/static/vendor/conversation-visuals';
await rm(outdir, { recursive: true, force: true });
await mkdir(outdir, { recursive: true });
await build({ stdin: { contents: `
    export {default as mermaid} from 'mermaid';
    export {default as katex} from 'katex';
    import DOMPurify from 'dompurify';
    export function sanitiseSvg(svg) {
        return DOMPurify.sanitize(svg, {USE_PROFILES: {svg: true, svgFilters: true},
            FORBID_TAGS: ['foreignObject', 'image', 'a'], FORBID_ATTR: ['href', 'xlink:href']});
    }`, resolveDir: process.cwd(), sourcefile: 'index.js' },
    outdir, entryNames: 'index', bundle: true, splitting: true, format: 'esm',
    minify: true, legalComments: 'linked', target: ['es2022'] });
await cp('node_modules/katex/dist/katex.min.css', `${outdir}/katex.min.css`);
await cp('node_modules/katex/dist/fonts', `${outdir}/fonts`, { recursive: true });
for (const name of ['mermaid', 'katex', 'dompurify']) {
    await cp(`node_modules/${name}/LICENSE`, `${outdir}/${name}-LICENSE`);
}
await writeFile(`${outdir}/README.txt`, 'Generated by npm run build:conversation-visuals from package-lock.json. Do not edit generated assets.\n');
