"""Canonical contracts for context bundles, dossiers, and reconstructed workspaces.

JVNAUTOSCI-254, JVNAUTOSCI-1563, JVNAUTOSCI-1564, and JVNAUTOSCI-1565 need one
authoritative catalogue for:

- the Vontology artefact vocabulary
- reusable workflow action IDs
- reconstructed-workspace keys
- schema versions for persisted state and benchmark output
"""

from __future__ import annotations

CONTEXT_BUNDLE_SCHEMA_VERSION = "context_bundle.v1"
CONTEXT_FACET_SCHEMA_VERSION = "context_facet.v1"
CONTEXT_DOSSIER_SCHEMA_VERSION = "context_dossier.v1"
WORKFLOW_REPORT_REVISION_SCHEMA_VERSION = "workflow_report_revision.v1"
EVIDENCE_RECEIPT_SCHEMA_VERSION = "evidence_receipt.v1"
RECONSTRUCTED_WORKSPACE_SCHEMA_VERSION = "reconstructed_workspace.v1"
CONTEXT_BUNDLE_BENCHMARK_SCHEMA_VERSION = "context_bundle_benchmark.v1"
CONTEXT_BUNDLE_BENCHMARK_SEED_SCHEMA_VERSION = (
    "context_bundle_benchmark.seed_bundle.v1"
)

CONTEXT_BUNDLE_TYPE_ID = "#V#context_bundle"
WORKFLOW_CONTEXT_BUNDLE_TYPE_ID = "#V#workflow_context_bundle"
CONCEPT_CONTEXT_BUNDLE_TYPE_ID = "#V#concept_context_bundle"
CONTEXT_FACET_TYPE_ID = "#V#context_facet"
CONTEXT_DOSSIER_TYPE_ID = "#V#context_dossier"
WORKFLOW_REPORT_REVISION_TYPE_ID = "#V#workflow_report_revision"
EVIDENCE_RECEIPT_TYPE_ID = "#V#evidence_receipt"

HAS_CONTEXT_BUNDLE_PREDICATE_ID = "#V#has_context_bundle"
CONTEXT_BUNDLE_EXTENDS_PREDICATE_ID = "#V#context_bundle_extends"
HAS_CONTEXT_FACET_PREDICATE_ID = "#V#has_context_facet"
HAS_CONTEXT_DOSSIER_PREDICATE_ID = "#V#has_context_dossier"
HAS_REPORT_REVISION_PREDICATE_ID = "#V#has_report_revision"
CITES_EVIDENCE_RECEIPT_PREDICATE_ID = "#V#cites_evidence_receipt"

CONTEXT_RESOLVE_EFFECTIVE_CONTEXT_ACTION_ID = "context.resolve_effective_context"
CONTEXT_ASSEMBLE_DOSSIER_ACTION_ID = "context.assemble_context_dossier"
CONTEXT_UPDATE_REPORT_REVISION_ACTION_ID = "context.update_report_revision"
CONTEXT_BUILD_RECONSTRUCTED_WORKSPACE_ACTION_ID = (
    "context.build_reconstructed_workspace"
)

WORKSPACE_KEY_QUESTION = "workspace_question"
WORKSPACE_KEY_TASK = "workspace_task"
WORKSPACE_KEY_EFFECTIVE_CONTEXT_BUNDLE_IDS = "effective_context_bundle_ids"
WORKSPACE_KEY_EFFECTIVE_CONTEXT_FACET_IDS = "effective_context_facet_ids"
WORKSPACE_KEY_CONTEXT_DOSSIER_ID = "context_dossier_id"
WORKSPACE_KEY_CONTEXT_DOSSIER = "context_dossier"
WORKSPACE_KEY_REPORT_REVISION_ID = "report_revision_id"
WORKSPACE_KEY_REPORT_REVISION = "report_revision"
WORKSPACE_KEY_IMMEDIATE_CONTEXT = "immediate_context"
WORKSPACE_KEY_OPEN_QUESTIONS = "open_questions"
WORKSPACE_KEY_EVIDENCE_RECEIPTS = "evidence_receipts"
WORKSPACE_KEY_INTERACTION_BUDGET = "interaction_budget"
WORKSPACE_KEY_TERMINATION_STATUS = "termination_status"
WORKSPACE_KEY_SEARCH_HISTORY = "search_history"
WORKSPACE_KEY_WORKSPACE_TELEMETRY = "workspace_reconstruction_telemetry"

WORKSPACE_KEYS: tuple[str, ...] = (
    WORKSPACE_KEY_QUESTION,
    WORKSPACE_KEY_TASK,
    WORKSPACE_KEY_EFFECTIVE_CONTEXT_BUNDLE_IDS,
    WORKSPACE_KEY_EFFECTIVE_CONTEXT_FACET_IDS,
    WORKSPACE_KEY_CONTEXT_DOSSIER_ID,
    WORKSPACE_KEY_CONTEXT_DOSSIER,
    WORKSPACE_KEY_REPORT_REVISION_ID,
    WORKSPACE_KEY_REPORT_REVISION,
    WORKSPACE_KEY_IMMEDIATE_CONTEXT,
    WORKSPACE_KEY_OPEN_QUESTIONS,
    WORKSPACE_KEY_EVIDENCE_RECEIPTS,
    WORKSPACE_KEY_INTERACTION_BUDGET,
    WORKSPACE_KEY_TERMINATION_STATUS,
    WORKSPACE_KEY_SEARCH_HISTORY,
    WORKSPACE_KEY_WORKSPACE_TELEMETRY,
)

DEFAULT_CONTEXT_BUNDLE_BENCHMARK_CASE_SET = "phase2_seed"

CONTEXT_BUNDLE_STRATEGY_BUNDLES_ONLY = "bundles_only"
CONTEXT_BUNDLE_STRATEGY_DOSSIER = "bundles_plus_dossier_reconstruction"
CONTEXT_BUNDLE_STRATEGY_REPORT_REVISION = (
    "bundles_plus_dossier_reconstruction_plus_report_revision"
)

CONTEXT_BUNDLE_STRATEGIES: tuple[str, ...] = (
    CONTEXT_BUNDLE_STRATEGY_BUNDLES_ONLY,
    CONTEXT_BUNDLE_STRATEGY_DOSSIER,
    CONTEXT_BUNDLE_STRATEGY_REPORT_REVISION,
)

CONTEXT_DOSSIER_BRANCH_KIND_THEORY_LOCAL = "theory_local"
CONTEXT_DOSSIER_BRANCH_KIND_COUNTERFACTUAL = "counterfactual"
CONTEXT_DOSSIER_BRANCH_KIND_ALTERNATIVE_INTERPRETATION = (
    "alternative_interpretation"
)

CONTEXT_DOSSIER_BRANCH_KINDS: frozenset[str] = frozenset(
    {
        CONTEXT_DOSSIER_BRANCH_KIND_THEORY_LOCAL,
        CONTEXT_DOSSIER_BRANCH_KIND_COUNTERFACTUAL,
        CONTEXT_DOSSIER_BRANCH_KIND_ALTERNATIVE_INTERPRETATION,
    }
)

__all__ = [
    "CITES_EVIDENCE_RECEIPT_PREDICATE_ID",
    "CONCEPT_CONTEXT_BUNDLE_TYPE_ID",
    "CONTEXT_ASSEMBLE_DOSSIER_ACTION_ID",
    "CONTEXT_BUNDLE_BENCHMARK_SCHEMA_VERSION",
    "CONTEXT_BUNDLE_BENCHMARK_SEED_SCHEMA_VERSION",
    "CONTEXT_BUNDLE_EXTENDS_PREDICATE_ID",
    "CONTEXT_BUNDLE_SCHEMA_VERSION",
    "CONTEXT_BUNDLE_STRATEGIES",
    "CONTEXT_BUNDLE_STRATEGY_BUNDLES_ONLY",
    "CONTEXT_BUNDLE_STRATEGY_DOSSIER",
    "CONTEXT_BUNDLE_STRATEGY_REPORT_REVISION",
    "CONTEXT_BUNDLE_TYPE_ID",
    "CONTEXT_BUILD_RECONSTRUCTED_WORKSPACE_ACTION_ID",
    "CONTEXT_DOSSIER_BRANCH_KINDS",
    "CONTEXT_DOSSIER_BRANCH_KIND_ALTERNATIVE_INTERPRETATION",
    "CONTEXT_DOSSIER_BRANCH_KIND_COUNTERFACTUAL",
    "CONTEXT_DOSSIER_BRANCH_KIND_THEORY_LOCAL",
    "CONTEXT_DOSSIER_SCHEMA_VERSION",
    "CONTEXT_DOSSIER_TYPE_ID",
    "CONTEXT_FACET_SCHEMA_VERSION",
    "CONTEXT_FACET_TYPE_ID",
    "CONTEXT_RESOLVE_EFFECTIVE_CONTEXT_ACTION_ID",
    "CONTEXT_UPDATE_REPORT_REVISION_ACTION_ID",
    "DEFAULT_CONTEXT_BUNDLE_BENCHMARK_CASE_SET",
    "EVIDENCE_RECEIPT_SCHEMA_VERSION",
    "EVIDENCE_RECEIPT_TYPE_ID",
    "HAS_CONTEXT_BUNDLE_PREDICATE_ID",
    "HAS_CONTEXT_DOSSIER_PREDICATE_ID",
    "HAS_CONTEXT_FACET_PREDICATE_ID",
    "HAS_REPORT_REVISION_PREDICATE_ID",
    "RECONSTRUCTED_WORKSPACE_SCHEMA_VERSION",
    "WORKFLOW_CONTEXT_BUNDLE_TYPE_ID",
    "WORKFLOW_REPORT_REVISION_SCHEMA_VERSION",
    "WORKFLOW_REPORT_REVISION_TYPE_ID",
    "WORKSPACE_KEYS",
    "WORKSPACE_KEY_CONTEXT_DOSSIER",
    "WORKSPACE_KEY_CONTEXT_DOSSIER_ID",
    "WORKSPACE_KEY_EFFECTIVE_CONTEXT_BUNDLE_IDS",
    "WORKSPACE_KEY_EFFECTIVE_CONTEXT_FACET_IDS",
    "WORKSPACE_KEY_EVIDENCE_RECEIPTS",
    "WORKSPACE_KEY_IMMEDIATE_CONTEXT",
    "WORKSPACE_KEY_INTERACTION_BUDGET",
    "WORKSPACE_KEY_OPEN_QUESTIONS",
    "WORKSPACE_KEY_QUESTION",
    "WORKSPACE_KEY_REPORT_REVISION",
    "WORKSPACE_KEY_REPORT_REVISION_ID",
    "WORKSPACE_KEY_SEARCH_HISTORY",
    "WORKSPACE_KEY_TASK",
    "WORKSPACE_KEY_TERMINATION_STATUS",
    "WORKSPACE_KEY_WORKSPACE_TELEMETRY",
]
