"""Shared constants for semantic paper recommendation materialisation."""

from __future__ import annotations

SCHOLARLY_ARTICLE_TYPE_ID = "#V#scholarly_article"

PAPER_RECOMMENDATION_POLICY_VERSION = "paper_recommendation_policy.v2.semantic"

GENERIC_PAPER_MATCH_PROFILE_JSON_PREDICATE_ID = "#V#has_paper_matching_profile_json"
PAPER_RECOMMENDATION_ASSERTION_TYPE_ID = "#V#paper_recommendation_assertion"
HAS_PAPER_RECOMMENDATION_ASSERTION_PREDICATE_ID = (
    "#V#has_paper_recommendation_assertion"
)
PAPER_RECOMMENDATION_ASSERTS_PAPER_PREDICATE_ID = "#V#recommends_paper"
PAPER_RECOMMENDATION_ASSERTS_SUBJECT_PREDICATE_ID = "#V#recommendation_subject"
PAPER_RECOMMENDATION_EVALUATION_JSON_PREDICATE_ID = (
    "#V#has_paper_recommendation_evaluation_json"
)
PAPER_RECOMMENDATION_DELIVERED_VIA_MESSAGE_PREDICATE_ID = (
    "#V#paper_recommendation_delivered_via_message"
)
PAPER_RECOMMENDATION_FEEDBACK_TYPE_ID = "#V#paper_recommendation_feedback"
HAS_PAPER_RECOMMENDATION_FEEDBACK_PREDICATE_ID = "#V#has_paper_recommendation_feedback"
PAPER_RECOMMENDATION_FEEDBACK_ASSERTION_PREDICATE_ID = (
    "#V#paper_recommendation_feedback_assertion"
)
PAPER_RECOMMENDATION_FEEDBACK_PAPER_PREDICATE_ID = (
    "#V#paper_recommendation_feedback_paper"
)
PAPER_RECOMMENDATION_FEEDBACK_SUBJECT_PREDICATE_ID = (
    "#V#paper_recommendation_feedback_subject"
)
PAPER_RECOMMENDATION_FEEDBACK_PROFILE_PREDICATE_ID = (
    "#V#paper_recommendation_feedback_profile"
)
PAPER_RECOMMENDATION_FEEDBACK_JSON_PREDICATE_ID = (
    "#V#has_paper_recommendation_feedback_json"
)

PAPER_RECOMMENDATION_WORKFLOW_ID = "#V#paper_recommendation_evaluation_workflow"
PAPER_RECOMMENDATION_RERANK_PROMPT_CONCEPT_ID = (
    "#V#paper_recommendation_reranker_prompt"
)
PAPER_RECOMMENDATION_PROMPT_LINK_PREDICATE_ID = (
    "#V#uses_paper_recommendation_reranker_prompt"
)
PAPER_RECOMMENDATION_DELIVERY_PROMPT_CONCEPT_ID = (
    "#V#paper_recommendation_delivery_message_prompt"
)
PAPER_RECOMMENDATION_DELIVERY_PROMPT_LINK_PREDICATE_ID = (
    "#V#uses_paper_recommendation_delivery_message_prompt"
)

PAPER_RECOMMENDATION_REQUESTED_EVENT_TYPE = "paper_recommendation.requested"

DEFAULT_CANDIDATE_RECALL_LIMIT = 24
MAX_CANDIDATE_RECALL_LIMIT = 100
DEFAULT_MAX_RESULTS = 10
MAX_MAX_RESULTS = 50
DEFAULT_LLM_CANDIDATE_LIMIT = 12
MIN_RECOMMENDATION_SCORE = 0.55

SUMMARY_EXCERPT_CHARS = 280

__all__ = [
    "DEFAULT_CANDIDATE_RECALL_LIMIT",
    "DEFAULT_LLM_CANDIDATE_LIMIT",
    "DEFAULT_MAX_RESULTS",
    "GENERIC_PAPER_MATCH_PROFILE_JSON_PREDICATE_ID",
    "HAS_PAPER_RECOMMENDATION_ASSERTION_PREDICATE_ID",
    "HAS_PAPER_RECOMMENDATION_FEEDBACK_PREDICATE_ID",
    "MAX_CANDIDATE_RECALL_LIMIT",
    "MAX_MAX_RESULTS",
    "MIN_RECOMMENDATION_SCORE",
    "PAPER_RECOMMENDATION_ASSERTION_TYPE_ID",
    "PAPER_RECOMMENDATION_ASSERTS_PAPER_PREDICATE_ID",
    "PAPER_RECOMMENDATION_ASSERTS_SUBJECT_PREDICATE_ID",
    "PAPER_RECOMMENDATION_DELIVERED_VIA_MESSAGE_PREDICATE_ID",
    "PAPER_RECOMMENDATION_DELIVERY_PROMPT_CONCEPT_ID",
    "PAPER_RECOMMENDATION_DELIVERY_PROMPT_LINK_PREDICATE_ID",
    "PAPER_RECOMMENDATION_EVALUATION_JSON_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_ASSERTION_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_JSON_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_PAPER_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_PROFILE_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_SUBJECT_PREDICATE_ID",
    "PAPER_RECOMMENDATION_FEEDBACK_TYPE_ID",
    "PAPER_RECOMMENDATION_POLICY_VERSION",
    "PAPER_RECOMMENDATION_PROMPT_LINK_PREDICATE_ID",
    "PAPER_RECOMMENDATION_REQUESTED_EVENT_TYPE",
    "PAPER_RECOMMENDATION_RERANK_PROMPT_CONCEPT_ID",
    "PAPER_RECOMMENDATION_WORKFLOW_ID",
    "SCHOLARLY_ARTICLE_TYPE_ID",
    "SUMMARY_EXCERPT_CHARS",
]
