"""Shared constants for representation workflow routing coverage audits."""

from __future__ import annotations

REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_WORKFLOW_ID = (
    "#V#representation_workflow_routing_coverage_audit_workflow"
)

REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROMPT_CONCEPT_ID = (
    "#V#prompt_representation_workflow_routing_coverage_audit"
)
REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROMPT_LINK_PREDICATE = (
    "#V#hasRepresentationWorkflowRoutingCoverageAuditPrompt"
)

REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_TYPE_ID = (
    "#V#representation_workflow_routing_coverage_audit_profile"
)
REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_CONCEPT_ID = (
    "#V#representation_workflow_routing_coverage_audit_profile_default"
)
REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_PREDICATE = (
    "#V#hasRepresentationWorkflowRoutingCoverageAuditProfileJson"
)
REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_LINK_PREDICATE = (
    "#V#hasRepresentationWorkflowRoutingCoverageAuditProfile"
)

REPRESENTATION_ROUTING_AUDIT_LOAD_PROFILE_ACTION_ID = (
    "representation_routing_audit.load_profile"
)
REPRESENTATION_ROUTING_AUDIT_COLLECT_EVIDENCE_ACTION_ID = (
    "representation_routing_audit.collect_evidence"
)
REPRESENTATION_ROUTING_AUDIT_BUILD_EPISODE_EVIDENCE_ACTION_ID = (
    "representation_routing_audit.build_episode_evidence"
)
REPRESENTATION_ROUTING_AUDIT_FINALISE_ACTION_ID = (
    "representation_routing_audit.finalise"
)

REPRESENTATION_ROUTING_AUDIT_PROFILE_SCHEMA_VERSION = (
    "representation_workflow_routing_coverage_audit_profile.v1"
)
REPRESENTATION_ROUTING_AUDIT_REPORT_SCHEMA_VERSION = (
    "representation_workflow_routing_coverage_audit_report.v1"
)

CANONICAL_REPRESENTATION_ROUTING_AUDIT_WORKFLOW_IDS: tuple[str, ...] = (
    REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_WORKFLOW_ID,
)

__all__ = [
    "CANONICAL_REPRESENTATION_ROUTING_AUDIT_WORKFLOW_IDS",
    "REPRESENTATION_ROUTING_AUDIT_BUILD_EPISODE_EVIDENCE_ACTION_ID",
    "REPRESENTATION_ROUTING_AUDIT_COLLECT_EVIDENCE_ACTION_ID",
    "REPRESENTATION_ROUTING_AUDIT_FINALISE_ACTION_ID",
    "REPRESENTATION_ROUTING_AUDIT_LOAD_PROFILE_ACTION_ID",
    "REPRESENTATION_ROUTING_AUDIT_PROFILE_SCHEMA_VERSION",
    "REPRESENTATION_ROUTING_AUDIT_REPORT_SCHEMA_VERSION",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_CONCEPT_ID",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_LINK_PREDICATE",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_PREDICATE",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROFILE_TYPE_ID",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROMPT_CONCEPT_ID",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_PROMPT_LINK_PREDICATE",
    "REPRESENTATION_WORKFLOW_ROUTING_COVERAGE_AUDIT_WORKFLOW_ID",
]
