"""Shared constants for the Testing Workflows framework.

Keep canonical concept IDs, workflow IDs, action IDs, and schema versions in
one place so services, MCP handlers, and durable workflow actions stay aligned.
"""

from __future__ import annotations

TESTING_THEORY_SCHEMA_VERSION = "testing_theory.v1"
EXPERIMENT_SPEC_SCHEMA_VERSION = "experiment_spec.v1"
EXPERIMENT_RUN_SCHEMA_VERSION = "experiment_run.v1"
TESTING_EXPERIMENT_SCENARIO_TEMPLATE_SCHEMA_VERSION = (
    "testing_experiment_scenario_template.v1"
)
TESTING_REGRESSION_SUITE_POLICY_SCHEMA_VERSION = (
    "testing_regression_suite_policy.v1"
)

THEORY_TYPE_ID = "#V#theory"
TESTING_THEORY_TYPE_ID = "#V#testing_theory"
EPHEMERAL_THEORY_TYPE_ID = "#V#ephemeral_theory"
EXPERIMENT_SPEC_TYPE_ID = "#V#experiment_spec"
EXPERIMENT_RUN_TYPE_ID = "#V#experiment_run"
EXPERIMENT_SUITE_TYPE_ID = "#V#experiment_suite"
EXPERIMENT_OBSERVATION_TYPE_ID = "#V#experiment_observation"
PROMOTION_DECISION_TYPE_ID = "#V#promotion_decision"

INCLUDES_THEORY_PREDICATE_ID = "#V#includes_theory"
DERIVED_FROM_CANONICAL_CONCEPT_PREDICATE_ID = "#V#derived_from_canonical_concept"
HAS_ASSUMPTION_PREDICATE_ID = "#V#has_assumption"
HAS_HYPOTHESIS_PREDICATE_ID = "#V#has_hypothesis"
HAS_OBSERVATION_PREDICATE_ID = "#V#has_observation"
TESTS_CAPABILITY_PREDICATE_ID = "#V#tests_capability"
TESTS_WORKFLOW_PREDICATE_ID = "#V#tests_workflow"
USES_ISOLATION_MODE_PREDICATE_ID = "#V#uses_isolation_mode"
HAS_EXPECTED_OUTCOME_PREDICATE_ID = "#V#has_expected_outcome"
HAS_OBSERVED_OUTCOME_PREDICATE_ID = "#V#has_observed_outcome"
HAS_EXPERIMENT_VERDICT_PREDICATE_ID = "#V#has_experiment_verdict"
PROMOTION_REQUIRES_PREDICATE_ID = "#V#promotion_requires"
PROMOTES_TO_CANONICAL_RELATION_PREDICATE_ID = "#V#promotes_to_canonical_relation"
EXPIRES_AT_PREDICATE_ID = "#V#expires_at"
BELONGS_TO_EXPERIMENT_SUITE_PREDICATE_ID = "#V#belongs_to_experiment_suite"

MEETING_INVITATION_TESTING_WORKFLOW_ID = "#V#meeting_invitation_testing_workflow"
MEETING_INVITATION_CANDIDATE_WORKFLOW_ID = "#V#meeting_invitation_candidate_workflow"
PROMOTION_GATE_WORKFLOW_ID = "#V#promotion_gate_workflow"
SYNTHETIC_WORKFLOW_REGRESSION_SUITE_WORKFLOW_ID = (
    "#V#synthetic_workflow_regression_suite_workflow"
)
EPHEMERAL_THEORY_GC_WORKFLOW_ID = "#V#ephemeral_theory_gc_workflow"

CANONICAL_TESTING_WORKFLOW_IDS: tuple[str, ...] = (
    MEETING_INVITATION_TESTING_WORKFLOW_ID,
    MEETING_INVITATION_CANDIDATE_WORKFLOW_ID,
    PROMOTION_GATE_WORKFLOW_ID,
    SYNTHETIC_WORKFLOW_REGRESSION_SUITE_WORKFLOW_ID,
    EPHEMERAL_THEORY_GC_WORKFLOW_ID,
)

THEORY_CREATE_SLICE_ACTION_ID = "theory.create_slice"
THEORY_IMPORT_CANONICAL_CONTEXT_ACTION_ID = "theory.import_canonical_context"
THEORY_ASSERT_LOCAL_CLAIM_ACTION_ID = "theory.assert_local_claim"
THEORY_COMPUTE_DIFF_ACTION_ID = "theory.compute_diff"
THEORY_ROLLBACK_LOCAL_WRITES_ACTION_ID = "theory.rollback_local_writes"
THEORY_PROMOTE_VALIDATED_CLAIMS_ACTION_ID = "theory.promote_validated_claims"
THEORY_GC_EXPIRED_SLICES_ACTION_ID = "theory.gc_expired_slices"

EXPERIMENT_CREATE_SPEC_ACTION_ID = "experiment.create_spec"
EXPERIMENT_START_RUN_ACTION_ID = "experiment.start_run"
EXPERIMENT_RECORD_OBSERVATION_ACTION_ID = "experiment.record_observation"
EXPERIMENT_COMPUTE_VERDICT_ACTION_ID = "experiment.compute_verdict"
EXPERIMENT_EMIT_LEARNING_SIGNAL_ACTION_ID = "experiment.emit_learning_signal"
EXPERIMENT_EXECUTE_TARGET_WORKFLOW_ACTION_ID = "experiment.execute_target_workflow"
EXPERIMENT_EXECUTE_REGRESSION_SUITE_ACTION_ID = "experiment.execute_regression_suite"

TESTING_PREPARE_EXPERIMENT_SPEC_ACTION_ID = "testing.prepare_experiment_spec"
TESTING_PREPARE_MEETING_INVITATION_SPEC_ACTION_ID = (
    "testing.prepare_meeting_invitation_spec"
)

THEORY_ASSERTION_STATUS_PROPOSED = "proposed"
THEORY_ASSERTION_STATUS_PROMOTED = "promoted"
THEORY_ASSERTION_STATUS_ROLLED_BACK = "rolled_back"
THEORY_ASSERTION_STATUS_EXPIRED = "expired"
THEORY_ASSERTION_STATUSES: frozenset[str] = frozenset(
    {
        THEORY_ASSERTION_STATUS_PROPOSED,
        THEORY_ASSERTION_STATUS_PROMOTED,
        THEORY_ASSERTION_STATUS_ROLLED_BACK,
        THEORY_ASSERTION_STATUS_EXPIRED,
    }
)

EXPERIMENT_VERDICT_PASS = "pass"
EXPERIMENT_VERDICT_FAIL = "fail"
EXPERIMENT_VERDICT_PARTIAL = "partial"
EXPERIMENT_VERDICT_INCONCLUSIVE = "inconclusive"
EXPERIMENT_VERDICTS: frozenset[str] = frozenset(
    {
        EXPERIMENT_VERDICT_PASS,
        EXPERIMENT_VERDICT_FAIL,
        EXPERIMENT_VERDICT_PARTIAL,
        EXPERIMENT_VERDICT_INCONCLUSIVE,
    }
)

EXPERIMENT_RUN_STATUS_PENDING = "pending"
EXPERIMENT_RUN_STATUS_RUNNING = "running"
EXPERIMENT_RUN_STATUS_COMPLETED = "completed"
EXPERIMENT_RUN_STATUS_FAILED = "failed"
EXPERIMENT_RUN_STATUSES: frozenset[str] = frozenset(
    {
        EXPERIMENT_RUN_STATUS_PENDING,
        EXPERIMENT_RUN_STATUS_RUNNING,
        EXPERIMENT_RUN_STATUS_COMPLETED,
        EXPERIMENT_RUN_STATUS_FAILED,
    }
)

THEORY_LOCAL_TARGET_KIND_CONCEPT = "concept"
THEORY_LOCAL_TARGET_KIND_TEXT = "text"

THEORY_RUN_COLLECTION = "testing_theory_runs"
EXPERIMENT_RUNS_COLLECTION = "experiment_runs"

__all__ = [
    "BELONGS_TO_EXPERIMENT_SUITE_PREDICATE_ID",
    "CANONICAL_TESTING_WORKFLOW_IDS",
    "DERIVED_FROM_CANONICAL_CONCEPT_PREDICATE_ID",
    "EPHEMERAL_THEORY_GC_WORKFLOW_ID",
    "EPHEMERAL_THEORY_TYPE_ID",
    "EXPERIMENT_COMPUTE_VERDICT_ACTION_ID",
    "EXPERIMENT_CREATE_SPEC_ACTION_ID",
    "EXPERIMENT_EMIT_LEARNING_SIGNAL_ACTION_ID",
    "EXPERIMENT_EXECUTE_REGRESSION_SUITE_ACTION_ID",
    "EXPERIMENT_EXECUTE_TARGET_WORKFLOW_ACTION_ID",
    "EXPERIMENT_OBSERVATION_TYPE_ID",
    "EXPERIMENT_RECORD_OBSERVATION_ACTION_ID",
    "EXPERIMENT_RUN_SCHEMA_VERSION",
    "EXPERIMENT_RUN_TYPE_ID",
    "EXPERIMENT_RUN_STATUSES",
    "EXPERIMENT_RUN_STATUS_COMPLETED",
    "EXPERIMENT_RUN_STATUS_FAILED",
    "EXPERIMENT_RUN_STATUS_PENDING",
    "EXPERIMENT_RUN_STATUS_RUNNING",
    "EXPERIMENT_RUNS_COLLECTION",
    "EXPERIMENT_SPEC_SCHEMA_VERSION",
    "EXPERIMENT_SPEC_TYPE_ID",
    "EXPERIMENT_START_RUN_ACTION_ID",
    "EXPERIMENT_SUITE_TYPE_ID",
    "EXPERIMENT_VERDICT_FAIL",
    "EXPERIMENT_VERDICT_INCONCLUSIVE",
    "EXPERIMENT_VERDICT_PARTIAL",
    "EXPERIMENT_VERDICT_PASS",
    "EXPERIMENT_VERDICTS",
    "EXPIRES_AT_PREDICATE_ID",
    "HAS_ASSUMPTION_PREDICATE_ID",
    "HAS_EXPECTED_OUTCOME_PREDICATE_ID",
    "HAS_EXPERIMENT_VERDICT_PREDICATE_ID",
    "HAS_HYPOTHESIS_PREDICATE_ID",
    "HAS_OBSERVATION_PREDICATE_ID",
    "HAS_OBSERVED_OUTCOME_PREDICATE_ID",
    "INCLUDES_THEORY_PREDICATE_ID",
    "MEETING_INVITATION_CANDIDATE_WORKFLOW_ID",
    "MEETING_INVITATION_TESTING_WORKFLOW_ID",
    "PROMOTES_TO_CANONICAL_RELATION_PREDICATE_ID",
    "PROMOTION_DECISION_TYPE_ID",
    "PROMOTION_GATE_WORKFLOW_ID",
    "PROMOTION_REQUIRES_PREDICATE_ID",
    "SYNTHETIC_WORKFLOW_REGRESSION_SUITE_WORKFLOW_ID",
    "TESTING_PREPARE_MEETING_INVITATION_SPEC_ACTION_ID",
    "TESTING_PREPARE_EXPERIMENT_SPEC_ACTION_ID",
    "TESTING_EXPERIMENT_SCENARIO_TEMPLATE_SCHEMA_VERSION",
    "TESTING_REGRESSION_SUITE_POLICY_SCHEMA_VERSION",
    "TESTING_THEORY_SCHEMA_VERSION",
    "TESTING_THEORY_TYPE_ID",
    "TESTS_CAPABILITY_PREDICATE_ID",
    "TESTS_WORKFLOW_PREDICATE_ID",
    "THEORY_ASSERTION_STATUSES",
    "THEORY_ASSERTION_STATUS_EXPIRED",
    "THEORY_ASSERTION_STATUS_PROMOTED",
    "THEORY_ASSERTION_STATUS_PROPOSED",
    "THEORY_ASSERTION_STATUS_ROLLED_BACK",
    "THEORY_ASSERT_LOCAL_CLAIM_ACTION_ID",
    "THEORY_COMPUTE_DIFF_ACTION_ID",
    "THEORY_CREATE_SLICE_ACTION_ID",
    "THEORY_GC_EXPIRED_SLICES_ACTION_ID",
    "THEORY_IMPORT_CANONICAL_CONTEXT_ACTION_ID",
    "THEORY_LOCAL_TARGET_KIND_CONCEPT",
    "THEORY_LOCAL_TARGET_KIND_TEXT",
    "THEORY_PROMOTE_VALIDATED_CLAIMS_ACTION_ID",
    "THEORY_ROLLBACK_LOCAL_WRITES_ACTION_ID",
    "THEORY_RUN_COLLECTION",
    "THEORY_TYPE_ID",
    "USES_ISOLATION_MODE_PREDICATE_ID",
]
